name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonary analysis
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.11.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    #- name: Run tests
    #  run: mix test --cover --export-coverage jacoco
    #- name: Store coverage xml
    #  run: mix coveralls.xml
    #  if: ${{ always() }}
    #- name: Send coverage to codacy
    #  uses: codacy/codacy-coverage-reporter-action@master
    #  with:
    #    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
    #    coverage-reports: coverage.xml
    #  if: ${{ always() }}
    - name: Send coverage to coveralls
      run: mix coveralls.github
      if: ${{ always() }}
    - name: Scan for SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ always() }}
